### ISSUE TITLE
ECS Steps?

### ISSUE THREAD

**Issue by 4mp3d** [Ponjimon/vrising-docker#3]
Steps to do this in ECS for n00bs?

**Comment by Ponjimon** [comment]
Hi,

I can do a step-by-step tutorial next week, I'm currently not at home.

**Comment by Ponjimon** [comment]
Actually, after consideration, I decided against creating a tutorial for this as this would be out of the scope of this repository. The reason is that I cannot know which preferred way of deploying the image one wants on ECS as there are multiple ways to do so (EC2, Fargate, ECS Anywhere) nor can I make assumptions on the desired machine size (vCPUs, etc).

That being said, there are plenty of [tutorials](https://www.clairvoyant.ai/blog/deploy-and-run-docker-images-on-aws-ecs) out there explaining how you can run a Docker image on ECS.
