### ISSUE TITLE
Performance warning: Thread starvation

### ISSUE THREAD

**Issue by Jmag103** [Ponjimon/vrising-docker#6]
I'm getting this pretty constantly in my logs. Although the server runs pretty fine with 4-5 people. Haven't had more than that. Is anyone else getting this? Tried to allocate more cpu and memory to it in my docker-compose.yaml, but it doesn't seem to help. My CPU usage for the container reads around 160%

```
SteamLog [SDR k_ESteamNetworkingSocketsDebugOutputType_Warning] SteamNetworkingSockets lock held for 7.6ms.  (Performance warning.)  ServiceThread,ThinkPingProbes,EnsureDataCenterRoutesValid

This is usually a symptom of a general performance problem such as thread starvation.
```

**Comment by Ponjimon** [comment]
Yeah, I'm getting this as well. I can't tell if this is "normal" or not, like, are people getting this error as well even if they host it directly on a Windows machine? 

My guess is it's because of Wine emulation but as long as it's only showing those logs but not actually causing issues, not much we can do about it

**Comment by Jmag103** [comment]
Yea I was thinking it had something to do with the emulation as well. I saw some where in the logs it was reading the specs of a old windows 7 pentium desktop with 4 cores at 2.40ghz and it might be restricted by that.

**Comment by Ponjimon** [comment]
I pushed a new Docker image. Not sure if it would change anything but maybe you can try :)

**Comment by Jmag103** [comment]
I'll try it out on a test server and let you know if I see any changes
